### ISSUE TITLE
How to solve this problem ?

### ISSUE THREAD

**Issue by Luning10000** [JonathanWi/react-heatmap#1]
Browserify Error { [Error: Cannot find module 'heatmapjs/build/heatmap.js' from 'F:\react-heatmap\src']

**Comment by JonathanWi** [comment]
Fixed in `^1.0.6`, just update the component in your package.json and it will work fine :)

**Comment by JonathanWi** [comment]
@Luning10000 closing for now, tell me if the problem re-appears

**Comment by Luning10000** [comment]
ok  , thank you for your help!
