### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by williejay2017** [JonathanWi/react-heatmap#10]
./node_modules/react-heatmap/lib/ReactHeatmap.js

Line 96 for some reason its not recognizing this property. I am not sure why I am having this issue. I have tried uninstalling, npm cache clean --force, I get the same issues with this component. I used it a few months ago in another project and it worked perfectly. Now I am having issues.
![screen shot 2017-11-06 at 5 07 03 pm](https://user-images.githubusercontent.com/26513346/32469403-23d5f89e-c318-11e7-84a6-7c1b56698548.png)

**Comment by williejay2017** [comment]
I figured out the issue. react-heatmap is not yet supported by the latest version of react so I had to downgrade to 15.6.1. Ill just keep a watch and see if author updates.

**Comment by JoaoAlrc** [comment]
@williejay2017 nothing more?
